markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: ""

version: 0.3.0

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/kickserv/dojo
